### PR TITLE
Labelheight

### PR DESCRIPTION
**Pull request by devanshimodha**
# Description

Label in dropdown won't be truncated now and the height will increase according to the text.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe on what device it is tested

* Xcode: 12.0.1
* Model name: iPhone SE (2nd generation) OS 13.5
11 Pro Max OS 13.5
11 Pro Max OS 14.0

Simulator Screen Shot - iPhone 11 Pro - 2020-10-16 at 14 42 14

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# Reviewers:

Please tag relevant people requesting a review

### CODE REVIEW

**Comment by tejuamirthi** [comment]
Hey @devanshimodha . Thank you for contributing! 
I'd like to mention you tick the relevant check boxes in the pr and also can you share a screenshot of the output?

This issue is assigned to you now.

**Review by tejuamirthi — CHANGES_REQUESTED** [review]
Can you please not add changes to .DS_Store file? Remove changes to the file and update the pr. If possible can you add this file extension to .gitignore? feel free to comment and let me know. Thanks!

**Comment by devanshimodha** [comment]
Please check now and let me know if anything else is needed

**Comment by tejuamirthi** [comment]
> Please check now and let me know if anything else is needed

Well done.
Thank you so much @devanshimodha ! 

Feel free to create any issue you have encountered or any feature request you'd like to have in this project and work on it. Once again thanks and keep it up!

**Review by tejuamirthi — APPROVED** [review]

**Pull request merged**
