### PR TITLE
Refactor Code

### PR DESCRIPTION
**Pull request by iskandir**
start refactoring your code in CustomDropDown.swift.

You can use my layout for future documentation, I think it's pretty nice. Works fine for me :)

CustomDropDownPresenter.swift not complete?

Greetings!
****************************************************************************************************************
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe on what device it is tested

* Xcode:
* Model name:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# Reviewers:

Please tag relevant people requesting a review

### CODE REVIEW

**Comment by iskandir** [comment]
Please add #Hacktoberfest Tag to your project. 
Thanks 👍

**Comment by tejuamirthi** [comment]
Hey @iskandir thank you for your interest. I'm glad you are trying to contribute but there are other changes going on in this project. So, you need to wait for some more time for this to be merged and there might be changes as well. That you need to update your branch later and make the necessary description and changes accordingly. Thanks again! Feel free to create new issues and raise prs for other issues

**Review by tejuamirthi — CHANGES_REQUESTED** [review]
You'll need to update this branch after the current pull request #11 
Please check other issues till then. Thanks!

**Comment by tejuamirthi** [comment]
Are you working on this @iskandir

**Pull request closed without merging**
