### PR TITLE
Handling reuse for tableview cell to resolve Overlap Text

### PR DESCRIPTION
**Pull request by devanshimodha**
# Description

Text Overlap has been Resolved

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

By scrolling the dropdown view

Please describe on what device it is tested

* Xcode: 12.0
* Model name: iPhone SE (2nd Generation)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# Reviewers:

@tejuamirthi

### CODE REVIEW

**Comment by tejuamirthi** [comment]
Please resolve the conflicts in your pr, will review this in the morning tomorrow

**Comment by devanshimodha** [comment]
Please check whether the conflicts are resolved

**Comment by tejuamirthi** [comment]
No, conflicts are still there. I think you need to sync your repo with upstream and try taking a pull @devanshimodha  

[Refer here](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository)

**Comment by devanshimodha** [comment]
> No, conflicts are still there. I think you need to sync your repo with upstream and try taking a pull @devanshimodha
> 
> [Refer here](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository)

Done @tejuamirthi

**Review by tejuamirthi — APPROVED** [review]
Thank you for the contribution @devanshimodha.
I will merge this in some time. Approved.

You can contribute to new issues and create prs

**Pull request merged**
